#!/bin/sh

# MIT License

# Copyright (c) 2025 Alex Gvozdik

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Instructions:
# - place this file in .git/hooks/prepare-commit-msg of the project
# - run `chmod +x` against it to make it executable (git needs it)
# - when [xxx-123] is not desired, start commit message with an open square bracket, ie [
# Script will extract 'xxx-1234' from after last found '/'
#  '/' is therefore required as a pre-requisite

currentMessage=$(cat "$1")
extractedTicketNumber=`git branch | grep '^\*' | sed -E -e 's/.*\/([^-]*-[0-9]+).*/\1/'`

# 1. sed won't replace if it doesn't find a match, 
#  check if not starting with * (sed doesn't filter something like '* develop')
# 2. check if starts with open square bracket, ie '[' to allow override
if [[ "$extractedTicketNumber" != "*"* ]] \
  && [[ "$currentMessage" != "["* ]]; then
	# prepend ticket number to the current message
  echo "[$extractedTicketNumber]" "$currentMessage" > "$1"
fi